# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Paycheck', 'Paycheck'), ('Bonus', 'Bonus'), ('Other', 'Other')], max_length=100)),
                ('name', models.CharField(max_length=100, null=True)),
                ('value', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=100)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Drinks', 'Drinks'), ('Entertainment', 'Entertainment'), ('Personal', 'Personal'), ('Health', 'Health'), ('Home', 'Home'), ('Clothes & Stuff', 'Clothes & Stuff'), ('Gifts', 'Gifts'), ('Taxes', 'Taxes'), ('Other', 'Other')], max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_budget.Month')),
            ],
        ),
        migrations.AddField(
            model_name='income',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_budget.Month'),
        ),
    ]
